from pydantic import BaseModel, ConfigDict, Field


class VideoDataSubtitle(BaseModel):
    language: str
    source: str
    format: str
    url: str
    is_auto_generated: bool = Field(default=False, alias="isAutoGenerated")

    model_config = ConfigDict(populate_by_name=True)


class VideoTranslationHelpObject(BaseModel):
    target: str
    target_url: str = Field(alias="targetUrl")

    model_config = ConfigDict(populate_by_name=True)


class VideoData(BaseModel):
    url: str
    video_id: str = Field(alias="videoId")
    host: str
    duration: float | None = None
    title: str | None = None
    description: str | None = None
    subtitles: list[VideoDataSubtitle] = []
    translation_help: list[VideoTranslationHelpObject] | None = Field(
        default=None, alias="translationHelp"
    )

    model_config = ConfigDict(populate_by_name=True)


class TranslationResponse(BaseModel):
    translation_id: str = Field(alias="translationId")
    translated: bool
    url: str | None = None
    status: int
    remaining_time: int = Field(default=-1, alias="remainingTime")
    message: str | None = None

    model_config = ConfigDict(populate_by_name=True)


class SubtitleItem(BaseModel):
    language: str
    url: str
    translated_language: str | None = Field(default=None, alias="translatedLanguage")
    translated_url: str | None = Field(default=None, alias="translatedUrl")

    model_config = ConfigDict(populate_by_name=True)


class GetSubtitlesResponse(BaseModel):
    waiting: bool
    subtitles: list[SubtitleItem]


class StreamTranslationObject(BaseModel):
    url: str
    timestamp: str


class StreamTranslationResponse(BaseModel):
    translated: bool
    interval: int
    ping_id: int | None = Field(default=None, alias="pingId")
    result: StreamTranslationObject | None = None
    message: str | None = None

    model_config = ConfigDict(populate_by_name=True)
